import { CheckCircle2, Cpu, KeyRound, RefreshCw, Save, TestTube2, XCircle } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import type { ModelCapability, ModelEndpointSettings } from '../../api/model-settings'
import { Alert } from '../../components/feedback/alert'
import { LoadingState } from '../../components/feedback/state-views'
import { Button } from '../../components/ui/button'
import { useModelSettingsQuery, useProviderModelsMutation, useSaveModelSettingsMutation, useTestModelProviderMutation } from './queries'

type FormState = { name: string; baseUrl: string; authMode: 'bearer' | 'none'; apiStyle: 'openai_chat_completions' | 'openai_responses' | 'openai_embeddings'; apiKey: string; clearApiKey: boolean; model: string; embeddingDimension: number; embeddingInputType: 'none' | 'query' | 'passage'; timeoutSeconds: number; enabled: boolean }
function initialForm(capability: ModelCapability, provider: ModelEndpointSettings | null): FormState {
  return provider ? { name: provider.name, baseUrl: provider.baseUrl, authMode: provider.authMode === 'none' ? 'none' : 'bearer', apiStyle: provider.apiStyle, apiKey: '', clearApiKey: false, model: provider.model, embeddingDimension: provider.embeddingDimension ?? 1536, embeddingInputType: provider.baseUrl.includes('integrate.api.nvidia.com') ? 'none' : provider.embeddingInputType ?? 'none', timeoutSeconds: provider.timeoutSeconds, enabled: provider.enabled } : { name: capability === 'chat' ? 'chat-provider' : 'embedding-provider', baseUrl: '', authMode: 'bearer', apiStyle: capability === 'chat' ? 'openai_chat_completions' : 'openai_embeddings', apiKey: '', clearApiKey: false, model: '', embeddingDimension: 1536, embeddingInputType: 'none', timeoutSeconds: 120, enabled: true }
}
function TestResult({ result }: { result?: { status: string; message: string; dimension: number | null } }) {
  if (!result) return null
  const passed = result.status === 'passed'
  const classes = passed
    ? 'rounded-lg border border-[var(--color-success-200)] bg-[var(--color-success-50)] p-3 text-sm text-[var(--color-success-700)]'
    : 'rounded-lg border border-[var(--color-danger-200)] bg-[var(--color-danger-50)] p-3 text-sm text-[var(--color-danger)]'
  return <div className={classes}><p className="flex items-center gap-2 font-semibold">{passed ? <CheckCircle2 className="size-4" /> : <XCircle className="size-4" />}{passed ? '连接成功' : '连接失败'}</p><p className="mt-1">{result.message}{result.dimension ? `（维度 ${result.dimension}）` : ''}</p></div>
}
function ProviderForm({ capability, title, description, provider }: { capability: ModelCapability; title: string; description: string; provider: ModelEndpointSettings | null }) {
  const [form, setForm] = useState<FormState>(() => initialForm(capability, provider))
  const save = useSaveModelSettingsMutation(); const catalog = useProviderModelsMutation(); const test = useTestModelProviderMutation()
  const set = <K extends keyof FormState>(key: K, value: FormState[K]) => setForm((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); save.mutate({ capability, input: { name: form.name, baseUrl: form.baseUrl, authMode: form.authMode, apiStyle: form.apiStyle, apiKey: form.apiKey || undefined, clearApiKey: form.clearApiKey, model: form.model, embeddingDimension: capability === 'embedding' ? form.embeddingDimension : null, embeddingInputType: capability === 'embedding' ? form.embeddingInputType : null, timeoutSeconds: form.timeoutSeconds, enabled: form.enabled } }, { onSuccess: () => setForm((current) => ({ ...current, apiKey: '', clearApiKey: false })) }) }
  return <form onSubmit={submit} className="space-y-5 rounded-xl border border-[var(--color-border)] bg-white p-6 shadow-sm">
    <div><h3 className="text-lg font-semibold">{title}</h3><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{description}</p></div>
    {capability === 'chat' ? <label className="block text-sm font-medium">接口协议<select className="mt-2 w-full rounded-md border p-2" value={form.apiStyle} onChange={(e) => set('apiStyle', e.target.value as 'openai_chat_completions' | 'openai_responses')}><option value="openai_chat_completions">OpenAI Chat Completions</option><option value="openai_responses">OpenAI Responses API</option></select></label> : null}
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">配置名称<input className="mt-2 w-full rounded-md border p-2" value={form.name} onChange={(e) => set('name', e.target.value)} required /></label><label className="text-sm font-medium">Base URL / 完整 Endpoint<input className="mt-2 w-full rounded-md border p-2" placeholder={capability === 'chat' && form.apiStyle === 'openai_responses' ? 'https://provider.example.com/v1/responses' : 'https://provider.example.com/v1'} value={form.baseUrl} onChange={(e) => set('baseUrl', e.target.value)} required /></label><label className="text-sm font-medium">鉴权方式<select className="mt-2 w-full rounded-md border p-2" value={form.authMode} onChange={(e) => set('authMode', e.target.value as 'bearer' | 'none')}><option value="bearer">Bearer API Key</option><option value="none">无鉴权（本地模型）</option></select></label><label className="text-sm font-medium"><span className="flex items-center gap-2"><KeyRound className="size-4" />API Key</span><input type="password" autoComplete="new-password" className="mt-2 w-full rounded-md border p-2" placeholder={provider?.apiKeyConfigured ? '已配置；留空保持不变' : '输入 API Key'} value={form.apiKey} disabled={form.authMode === 'none'} onChange={(e) => set('apiKey', e.target.value)} /></label></div>
    {provider?.apiKeyConfigured && form.authMode === 'bearer' ? <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.clearApiKey} onChange={(e) => set('clearApiKey', e.target.checked)} />清除已保存的 API Key</label> : null}
    <div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">{capability === 'chat' ? 'Chat 模型' : 'Embedding 模型'}<input list={`models-${capability}`} className="mt-2 w-full rounded-md border p-2" value={form.model} onChange={(e) => set('model', e.target.value)} required /></label>{capability === 'embedding' ? <><label className="text-sm font-medium">Embedding 维度<input type="number" min={1} className="mt-2 w-full rounded-md border p-2" value={form.embeddingDimension} onChange={(e) => set('embeddingDimension', Number(e.target.value))} /></label><label className="text-sm font-medium">输入类型<select className="mt-2 w-full rounded-md border p-2" value={form.embeddingInputType} onChange={(e) => set('embeddingInputType', e.target.value as 'none' | 'query' | 'passage')}><option value="none">不发送（标准 OpenAI）</option><option value="query">query（问题/搜索词）</option><option value="passage">passage（文档内容）</option></select></label></> : null}<label className="text-sm font-medium">超时（秒）<input type="number" min={1} max={600} className="mt-2 w-full rounded-md border p-2" value={form.timeoutSeconds} onChange={(e) => set('timeoutSeconds', Number(e.target.value))} /></label></div>
    <datalist id={`models-${capability}`}>{catalog.data?.map((model) => <option key={model} value={model} />)}</datalist><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.enabled} onChange={(e) => set('enabled', e.target.checked)} />启用此配置</label>
    <div className="flex flex-wrap gap-3 border-t pt-4"><Button type="submit" disabled={save.isPending}><Save className="size-4" />保存 {title}</Button><Button variant="secondary" onClick={() => catalog.mutate(capability)} disabled={catalog.isPending}><RefreshCw className={catalog.isPending ? 'size-4 animate-spin' : 'size-4'} />拉取模型</Button><Button variant="secondary" onClick={() => test.mutate(capability)} disabled={test.isPending}><TestTube2 className="size-4" />测试连接</Button></div>
    {save.isSuccess ? <Alert tone="success">已保存并立即生效。</Alert> : null}{save.isError ? <Alert tone="danger">{save.error.message}</Alert> : null}{catalog.isSuccess ? <Alert tone="info">发现 {catalog.data.length} 个模型。</Alert> : null}{catalog.isError ? <Alert tone="danger">{catalog.error.message}</Alert> : null}<TestResult result={test.data?.result} />{test.data?.requestId ? <p className="text-xs text-slate-500">Request ID: {test.data.requestId}</p> : null}
  </form>
}
export function ModelSettingsPage() {
  const query = useModelSettingsQuery()
  if (query.isPending) return <LoadingState message="正在加载模型设置…" />
  if (query.isError) return <Alert tone="danger" title="模型设置加载失败" action={<Button onClick={() => void query.refetch()}>重试</Button>}><p>{query.error.message}</p></Alert>
  return <section className="mx-auto max-w-6xl"><div className="flex items-start gap-3"><div className="rounded-xl bg-[var(--color-primary-50)] p-3 text-[var(--color-primary-700)]"><Cpu className="size-6" /></div><div><h2 className="text-2xl font-semibold">模型设置</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Chat 与 Embedding 使用完全独立的服务配置，可以分别接入不同公司。</p></div></div><div className="mt-6 grid gap-6 xl:grid-cols-2"><ProviderForm key={query.data.chat?.updatedAt ?? 'new-chat'} capability="chat" title="Chat 服务" description="用于制度问答、摘要和 Agent 生成。" provider={query.data.chat} /><ProviderForm key={query.data.embedding?.updatedAt ?? 'new-embedding'} capability="embedding" title="Embedding 服务" description="用于向量化和 Embedding 连通性验证。" provider={query.data.embedding} /></div><Alert className="mt-5" tone="warning">若检索由独立 LightRAG 服务执行，LightRAG 服务端的 Embedding 配置也需要与这里保持一致。</Alert></section>
}
