"""SQLModel metadata registration."""

from sqlmodel import SQLModel

from backend.app.db.models import (
    AgentRun,
    AIQueryLog,
    AuditEvent,
    AuditLog,
    Conversation,
    Department,
    Draft,
    EmbeddingVersion,
    EvalCase,
    EvalResult,
    EvalRun,
    FAQDraft,
    GraphCheckpointBinding,
    IdempotencyRecord,
    KnowledgeBase,
    KnowledgeBasePermission,
    KnowledgeDocument,
    Material,
    MaterialVersion,
    MCPServer,
    MemoryItem,
    Message,
    ModelProvider,
    ObjectVersion,
    QueryFeedback,
    RagIndexJob,
    ReconciliationIssue,
    RetrievalEvalItem,
    Role,
    RunEvent,
    Skill,
    Tenant,
    Tool,
    ToolCallLog,
    User,
    UserRole,
    UserRoleGrant,
    VectorManifest,
)

Base = SQLModel

__all__ = [
    "AIQueryLog",
    "AgentRun",
    "AuditEvent",
    "AuditLog",
    "Base",
    "Conversation",
    "Draft",
    "EmbeddingVersion",
    "EvalCase",
    "EvalResult",
    "EvalRun",
    "FAQDraft",
    "GraphCheckpointBinding",
    "IdempotencyRecord",
    "Department",
    "KnowledgeBase",
    "KnowledgeBasePermission",
    "KnowledgeDocument",
    "MCPServer",
    "Material",
    "MaterialVersion",
    "MemoryItem",
    "Message",
    "ModelProvider",
    "ObjectVersion",
    "QueryFeedback",
    "RagIndexJob",
    "ReconciliationIssue",
    "RetrievalEvalItem",
    "RunEvent",
    "Skill",
    "Role",
    "Tenant",
    "Tool",
    "ToolCallLog",
    "User",
    "UserRole",
    "UserRoleGrant",
    "VectorManifest",
]
