import { expect, test } from '@playwright/test'

test('admin reviews FAQ, inspects audit, runs answer evaluation, and debugs retrieval', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/login')
  await page.getByLabel('用户名').fill('admin')
  await page.getByLabel('密码').fill('frontend-e2e-only')
  await page.getByRole('button', { name: '登录' }).click()

  await page.getByRole('link', { name: 'FAQ 审核' }).click()
  const firstFAQ = page.getByRole('article').filter({ hasText: '常见问题 1' })
  const secondFAQ = page.getByRole('article').filter({ hasText: '常见问题 2' })
  await expect(firstFAQ).toContainText('F5 Leave Policy')
  page.once('dialog', (dialog) => dialog.accept())
  await firstFAQ.getByRole('button', { name: '审核通过' }).click()
  await expect(page.getByRole('status')).toContainText('FAQ 文档索引状态')
  await secondFAQ.getByRole('button', { name: '驳回' }).click()
  const rejectDialog = page.getByRole('dialog')
  await rejectDialog.getByLabel('驳回原因').fill('E2E duplicate topic')
  await rejectDialog.getByRole('button', { name: '确认驳回' }).click()
  await expect(rejectDialog).not.toBeVisible()

  await page.getByRole('link', { name: '审计日志' }).click()
  await expect(page.getByRole('heading', { name: '审计日志', level: 2 })).toBeVisible()
  await page.getByRole('button', { name: '查看' }).first().click()
  const auditDialog = page.getByRole('dialog')
  await expect(auditDialog.getByText('脱敏详情')).toBeVisible()
  await expect(auditDialog.getByText('Request ID')).toBeVisible()
  await auditDialog.getByRole('button', { name: '关闭对话框' }).click()

  await page.getByRole('link', { name: '评估中心' }).click()
  await page.getByLabel('问题').fill('How is annual leave approved?')
  await page.getByLabel('知识库分类代码').fill('hr')
  await page.getByLabel('期望关键词（逗号分隔）').fill('manager approval')
  await page.getByLabel('期望来源标题（逗号分隔）').fill('Travel Policy')
  await page.getByRole('button', { name: '创建用例' }).click()
  await expect(page.getByText(/enabled · hr · How is annual leave approved/u)).toBeVisible()

  const typeGroup = page.getByRole('group', { name: '评估类型' })
  await typeGroup.getByLabel('检索').uncheck()
  await typeGroup.getByLabel('回答').check()
  await page.getByRole('group', { name: '回答用例' }).getByLabel('How is annual leave approved?').check()
  await page.getByLabel('Run 名称').fill(`F5 E2E ${Date.now()}`)
  await page.getByRole('button', { name: '启动评估' }).click()
  await expect(page.getByText('rag_answer:completed')).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText(/answer_accuracy=1/u)).toBeVisible()

  await page.getByLabel('调试查询').fill('annual leave')
  await page.getByLabel('调试知识库').selectOption({ label: '人力资源制度库' })
  await page.getByRole('button', { name: '运行调试' }).click()
  await expect(page.getByRole('cell', { name: 'Travel Policy' })).toBeVisible()
})
