import { expect, test } from '@playwright/test'

test('admin runs Skills, inspects redacted Tool logs, and manages mock MCP integrations', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/login')
  await page.getByLabel('用户名').fill('admin')
  await page.getByLabel('密码').fill('frontend-e2e-only')
  await page.getByRole('button', { name: '登录' }).click()

  await page.getByRole('link', { name: 'Skill 管理' }).click()
  await expect(page.getByRole('heading', { name: 'Skill 管理', level: 2 })).toBeVisible()
  const summaryRow = page.getByRole('row').filter({ hasText: 'summary' })
  await expect(summaryRow).toContainText('已实现')
  await summaryRow.getByRole('button', { name: '手动运行' }).click()
  const runDialog = page.getByRole('dialog', { name: '运行 summary' })
  await runDialog.getByLabel('运行参数').fill(JSON.stringify({ text: 'Annual leave requires approval.' }))
  await runDialog.getByRole('button', { name: '确认运行' }).click()
  await expect(runDialog.getByText(/Audit ID：/u)).toBeVisible()
  await expect(runDialog.getByText(/Request ID：/u)).toBeVisible()
  await runDialog.getByRole('button', { name: '关闭运行对话框' }).click()

  page.once('dialog', (dialog) => dialog.accept())
  await summaryRow.getByRole('button', { name: '禁用' }).click()
  await expect(summaryRow).toContainText('已禁用')
  page.once('dialog', (dialog) => dialog.accept())
  await summaryRow.getByRole('button', { name: '启用' }).click()
  await expect(summaryRow).toContainText('已启用')

  const toolRow = page.getByRole('row').filter({ hasText: 'mcp.call' }).first()
  await expect(toolRow).toContainText('success')
  await toolRow.getByRole('button', { name: '查看' }).click()
  const toolDialog = page.getByRole('dialog', { name: 'Tool 日志详情' })
  await toolDialog.getByText('脱敏输入参数').click()
  await expect(toolDialog).toContainText('[REDACTED]')
  await expect(toolDialog).toContainText('visible')
  await toolDialog.getByRole('button', { name: '关闭 Tool 日志详情' }).click()

  await page.getByRole('link', { name: 'MCP 集成' }).click()
  await expect(page.getByRole('heading', { name: 'MCP 集成', level: 2 })).toBeVisible()
  const seedCard = page.getByRole('article').filter({ hasText: 'frontend_f6_mock' })
  await expect(seedCard).toContainText('MOCK')
  await seedCard.getByRole('button', { name: '健康检查' }).click()
  await expect(page.getByRole('status')).toContainText('healthy')
  await expect(seedCard).toContainText('mcp.email.create_draft')

  await seedCard.getByRole('button', { name: '编辑' }).click()
  const editDialog = page.getByRole('dialog', { name: '编辑 MCP 集成' })
  await editDialog.getByLabel('名称').fill('frontend_f6_mock_updated')
  await editDialog.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText('frontend_f6_mock_updated')).toBeVisible()

  await page.getByRole('button', { name: '创建 MCP' }).click()
  const createDialog = page.getByRole('dialog', { name: '创建 MCP 集成' })
  await createDialog.getByLabel('名称').fill(`f6_ui_mock_${Date.now()}`)
  await createDialog.getByLabel('启用集成').check()
  await createDialog.getByRole('button', { name: '保存' }).click()
  await expect(page.getByText(/f6_ui_mock_/u)).toBeVisible()
})

test('employee cannot open F6 administration routes', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('用户名').fill('frontend_employee')
  await page.getByLabel('密码').fill('employee-password')
  await page.getByRole('button', { name: '登录' }).click()
  await expect(page.getByRole('button', { name: '退出登录' })).toBeVisible()

  await page.goto('/admin/skills')
  await expect(page.getByRole('alert').getByRole('heading', { name: '无访问权限' })).toBeVisible()
  await page.goto('/admin/integrations')
  await expect(page.getByRole('alert').getByRole('heading', { name: '无访问权限' })).toBeVisible()
})
